version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:6.0
    container_name: recipe-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    networks:
      - recipe-network

  # FastAPI backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipe-backend
    restart: always
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    networks:
      - recipe-network

  # React Native Expo frontend
  frontend:
    build:
      context: ./recipe
      dockerfile: Dockerfile
    container_name: recipe-frontend
    restart: always
    networks:
      - recipe-network

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: recipe-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - backend
      - frontend
    networks:
      - recipe-network

  # Certbot for SSL certificates (optional)
  certbot:
    image: certbot/certbot
    container_name: recipe-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  recipe-network:
    driver: bridge

volumes:
  mongodb_data: 