version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:6.0
    container_name: recipe-mongodb
    restart: always
    volumes:
      - mongodb_data:/data/db
    networks:
      - recipe-network
    # Only expose MongoDB internally, not to outside world
    expose:
      - "27017"

  # FastAPI backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: recipe-backend
    restart: always
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    networks:
      - recipe-network
    # Expose port for debugging during development
    expose:
      - "8000"

  # React Native Expo frontend
  frontend:
    build:
      context: ./recipe
      dockerfile: Dockerfile
    container_name: recipe-frontend
    restart: always
    networks:
      - recipe-network
    expose:
      - "80"

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: recipe-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d/recipeai.conf:/etc/nginx/conf.d/recipeai.conf
      - /etc/letsencrypt:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - backend
      - frontend
    networks:
      - recipe-network
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  # Certbot for SSL certificates
  certbot:
    image: certbot/certbot
    container_name: recipe-certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - recipe-network

networks:
  recipe-network:
    driver: bridge

volumes:
  mongodb_data: 